---
Name: sharedraftcontent
After: framework/routes#coreroutes
---
SiteTree:
  extensions:
    - ShareDraftContentSiteTreeExtension
CMSMain:
  extensions:
    - ShareDraftContentRequirementsExtension
CMSPageEditController:
  extensions:
    - ShareDraftContentCMSPageEditControllerExtension
Director:
  rules:
    'preview': 'ShareDraftController'
---