---
Name: sharedraftcontent
---
SiteTree:
  extensions:
    - ShareDraftContentSiteTreeExtension
CMSMain:
  extensions:
    - ShareDraftContentRequirementsExtension
CMSPageEditController:
  extensions:
    - ShareDraftContentCMSPageEditControllerExtension
---